services:
  mongodb:
    image: mongo:8.0
    container_name: portfolio-service-mongodb
    restart: unless-stopped
    ports:
      - '27018:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
